controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute




    
# config/routes.yaml
app_car_filter:
    path: /car/filter
    controller: App\Controller\CarController::filter
    methods: [GET]


car_show:
    path: /car/{id}
    controller: App\Controller\CarController::show
    requirements:
        id: \d+   