controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    
# config/routes.yaml

car_filter:
    path: '/car/filter'
    controller: 'App\Controller\CarController::filter'
